using System.Diagnostics;
using static Sorting;
using static Infrastructure;
int[] array = CreateArray(10);
PrintArray(array);
Stopwatch sw = new();
sw.Start();
SelectionSort(array);
sw.Stop();
Console.WriteLine($"time = {sw.ElapsedMilliseconds}");
PrintArray(array);
