using System.Diagnostics;
using static Sorting;
using static InfrastructureThis;
Stopwatch sw = new();
int[] selectionArray = 10000.CreateArray(1, 100);
int[] bubbleArray = selectionArray.EquatingArray();
int[] quickSort = selectionArray.EquatingArray();
int[] standartSort = selectionArray.EquatingArray();
int[] countingSort = selectionArray.EquatingArray();
int[] CountingSortTread = selectionArray.EquatingArray();
Console.WriteLine("сортировка для 10 000 элементов");
sw.Start();
bubbleArray.SortBubble();
sw.Stop();
Console.WriteLine($"SortBubble time = {sw.ElapsedMilliseconds}");
sw.Restart();
selectionArray.SortSelection();
sw.Stop();
Console.WriteLine($"SortSelection time = {sw.ElapsedMilliseconds}");
sw.Restart();
quickSort.QuickSort(0, quickSort.Length-1);
sw.Stop();
Console.WriteLine($"Quick Sort time = {sw.ElapsedMilliseconds}");
sw.Restart();
Array.Sort(standartSort);
sw.Stop();
Console.WriteLine($"Standart sort time = {sw.ElapsedMilliseconds}");
// sw.Restart();
// selectionArray.SortQuick(0, selectionArray.Length-1);
// sw.Stop();
// Console.WriteLine($"my Quick time = {sw.ElapsedMilliseconds}");
sw.Restart();
countingSort.CountingSort();
sw.Stop();
Console.WriteLine($"Counting Sort time = {sw.ElapsedMilliseconds}");
sw.Restart();
CountingSortTread.CountingSortThread(10);
sw.Stop();
Console.WriteLine($"Counting Sort with threads time = {sw.ElapsedMilliseconds}");

